[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "java -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
region = "us-west1"

[[services]]
name = "discovery-service"
internalPort = 8090
healthcheckPath = "/actuator/health"

[services.envs]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8090"

[[services.volumes]]
name = "backup-data"
mountPath = "/data/backups"

[[services.volumes]]
name = "log-data"
mountPath = "/var/log/oppfinder"